import { useSearchParams } from "react-router";

export default function ShockReport() {
  const [searchParams] = useSearchParams();

  const data = {
    storeName: searchParams.get("store") || "VisionTek",
    risk: searchParams.get("risk") || "Red",
    // נתוני שלושת המוצרים שדגמת
    items: [
      { name: "USB-C to USB-A", orig: 6.99, sale: 5.99, final: 5.10, discount: "27%" },
      { name: "HDMI 2.1 Cable", orig: 12.99, sale: 12.99, final: 11.05, discount: "15%" },
      { name: "USB-C to DisplayPort", orig: 22.99, sale: 19.99, final: 17.00, discount: "26%" }
    ]
  };

  const styles = {
    container: { backgroundColor: '#f1f5f9', minHeight: '100vh', padding: '40px 20px', fontFamily: 'sans-serif' },
    card: { maxWidth: '800px', margin: '0 auto', backgroundColor: '#ffffff', borderRadius: '16px', overflow: 'hidden', boxShadow: '0 20px 25px -5px rgba(0,0,0,0.1)' },
    header: { backgroundColor: '#0f172a', padding: '30px', color: '#ffffff', display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
    riskBadge: { backgroundColor: '#dc2626', color: '#ffffff', padding: '8px 16px', borderRadius: '8px', fontWeight: 'bold', fontSize: '14px', textTransform: 'uppercase' },
    section: { padding: '30px', borderBottom: '1px solid #f1f5f9' },
    table: { width: '100%', borderCollapse: 'collapse', marginTop: '20px' },
    th: { textAlign: 'left', padding: '12px', borderBottom: '2px solid #e2e8f0', color: '#64748b', fontSize: '12px', textTransform: 'uppercase' },
    td: { padding: '12px', borderBottom: '1px solid #f1f5f9', fontSize: '14px' },
    highlightRow: { backgroundColor: '#fef2f2', fontWeight: 'bold', color: '#b91c1c' },
    footer: { padding: '20px', textAlign: 'center', color: '#94a3b8', fontSize: '12px', backgroundColor: '#f8fafc' }
  };

  return (
    <div style={styles.container}>
      <div style={styles.card}>
        {/* Header עם ה-LED האדום */}
        <div style={styles.header}>
          <div>
            <h1 style={{ margin: 0, fontSize: '28px', fontWeight: '900', letterSpacing: '-1px' }}>PROFIT GUARD</h1>
            <p style={{ margin: 0, fontSize: '12px', color: '#94a3b8' }}>SYSTEMIC MARGIN AUDIT REPORT</p>
          </div>
          <div style={styles.riskBadge}>● {data.risk} RISK DETECTED</div>
        </div>

        {/* Diagnosis */}
        <div style={styles.section}>
          <h2 style={{ fontSize: '22px', fontWeight: 'bold', margin: '0 0 10px 0' }}>Margin Leak Diagnosis: {data.storeName}</h2>
          <p style={{ color: '#475569', lineHeight: '1.5' }}>
            Our audit identified an active <strong>Discount Stacking</strong> logic failure. 
            The system is currently allowing cumulative discounts that erode the contribution margin across multiple product categories.
          </p>
        </div>

        {/* Evidence Table */}
        <div style={styles.section}>
          <h3 style={{ fontSize: '14px', fontWeight: 'bold', color: '#0f172a', textTransform: 'uppercase', marginBottom: '15px' }}>Observed Leaks (Live Checkout Data)</h3>
          <table style={styles.table}>
            <thead>
              <tr>
                <th style={styles.th}>Product</th>
                <th style={styles.th}>MSRP</th>
                <th style={styles.th}>Sale</th>
                <th style={styles.th}>Final (Stacked)</th>
                <th style={styles.th}>Total Loss %</th>
              </tr>
            </thead>
            <tbody>
              {data.items.map((item, idx) => (
                <tr key={idx} style={item.discount === "27%" || item.discount === "26%" ? styles.highlightRow : {}}>
                  <td style={styles.td}>{item.name}</td>
                  <td style={styles.td}>${item.orig}</td>
                  <td style={styles.td}>${item.sale}</td>
                  <td style={styles.td}>${item.final}</td>
                  <td style={styles.td}>{item.discount}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Impact Message */}
        <div style={{ padding: '30px', backgroundColor: '#0f172a', color: '#e2e8f0' }}>
          <p style={{ margin: 0, fontSize: '14px', lineHeight: '1.6' }}>
            <span style={{ color: '#f87171', fontWeight: 'bold' }}>Critical Impact:</span> In hardware retail, a cumulative discount of <strong>26-27%</strong> typically exceeds the net product margin. 
            These orders are likely being processed at a <strong>net loss</strong> once transaction fees and logistics are factored in.
          </p>
        </div>

        <div style={styles.footer}>
          Generated by Profit Guard Engine • Confidential Audit • Render Node: Production
        </div>
      </div>
    </div>
  );
}