// app/routes/reports.$leadId.jsx
import { useSearchParams, useParams } from "@remix-run/react";

export default function ShockReport() {
  const { leadId } = useParams();
  const [searchParams] = useSearchParams();

  // משיכת נתונים מה-URL (או ערכי דיפולט ל-VisionTek)
  const data = {
    storeName: searchParams.get("store") || "VisionTek",
    originalPrice: parseFloat(searchParams.get("orig") || "22.99"),
    salePrice: parseFloat(searchParams.get("sale") || "19.99"),
    couponPercent: parseFloat(searchParams.get("cpn") || "15"),
    couponCode: searchParams.get("code") || "WELCOME15",
    risk: searchParams.get("risk") || "Yellow",
  };

  // לוגיקה פיננסית של Profit Guard
  const finalPrice = (data.salePrice * (1 - data.couponPercent / 100)).toFixed(2);
  const combinedDiscount = (((1 - finalPrice / data.originalPrice) * 100)).toFixed(1);

  const riskStyles = {
    Red: "bg-red-600 text-white",
    Yellow: "bg-yellow-500 text-black",
    Blue: "bg-blue-600 text-white"
  };

  return (
    <div className="min-h-screen bg-slate-100 p-4 md:p-12 font-sans text-slate-900">
      <div className="max-w-4xl mx-auto bg-white shadow-2xl rounded-2xl overflow-hidden border border-slate-200">
        
        {/* Header - Dark & Professional */}
        <div className="bg-slate-900 p-8 text-white flex justify-between items-center">
          <div className="space-y-1">
            <h1 className="text-3xl font-black tracking-tighter">PROFIT GUARD</h1>
            <p className="text-slate-400 text-xs uppercase tracking-widest">External Margin Audit Report</p>
          </div>
          <div className={`px-4 py-2 rounded-lg font-bold text-sm uppercase ${riskStyles[data.risk]}`}>
            {data.risk} Risk Level
          </div>
        </div>

        {/* Diagnosis Summary */}
        <div className="p-8 border-b border-slate-100">
          <h2 className="text-2xl font-bold mb-3">Diagnostic: Potential Margin Leak</h2>
          <p className="text-slate-600 text-lg">
            Storefront audit for <span className="font-bold text-slate-900">{data.storeName}</span> identified a 
            critical logic failure in discount combinations.
          </p>
        </div>

        {/* The Math - Visual Impact */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 p-8 bg-slate-50">
          <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
            <p className="text-xs text-slate-500 uppercase font-bold mb-2">Original MSRP</p>
            <p className="text-3xl font-light">${data.originalPrice}</p>
          </div>
          <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
            <p className="text-xs text-orange-600 uppercase font-bold mb-2">Active Sale Price</p>
            <p className="text-3xl font-bold text-orange-600">${data.salePrice}</p>
          </div>
          <div className="bg-red-50 p-6 rounded-xl border-2 border-red-500 shadow-sm">
            <p className="text-xs text-red-700 uppercase font-bold mb-2 underline">Effective Discount</p>
            <p className="text-4xl font-black text-red-700">{combinedDiscount}%</p>
          </div>
        </div>

        {/* Evidence Breakdown */}
        <div className="p-8 space-y-6">
          <div className="bg-slate-900 p-6 rounded-xl text-white">
            <h3 className="text-xs font-bold text-slate-500 uppercase mb-4">Audit Findings</h3>
            <ul className="space-y-4">
              <li className="flex items-center gap-3">
                <span className="w-2 h-2 bg-red-500 rounded-full"></span>
                <span className="text-sm">Stacking allowed: <span className="font-mono bg-slate-800 px-2 py-1 rounded">{data.couponCode}</span> applied over Sale pricing.</span>
              </li>
              <li className="flex items-center gap-3">
                <span className="w-2 h-2 bg-red-500 rounded-full"></span>
                <span className="text-sm">Unintended margin erosion of <span className="font-bold text-red-400">{combinedDiscount}%</span> vs. MSRP.</span>
              </li>
              <li className="flex items-center gap-3">
                <span className="w-2 h-2 bg-yellow-500 rounded-full"></span>
                <span className="text-sm">Likely negative contribution margin for low-margin SKUs.</span>
              </li>
            </ul>
          </div>
        </div>

        {/* Call to Action Footer */}
        <div className="p-8 bg-slate-50 border-t border-slate-200 text-center">
          <p className="text-slate-500 text-sm mb-4 italic">
            This is a read-only storefront audit. Profit Guard monitors these leaks in real-time.
          </p>
          <div className="text-xs text-slate-400">
            Report generated by Profit Guard Engine (Render Production Node)
          </div>
        </div>
      </div>
    </div>
  );
}